/*

 CTAGBMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : C:\c\ctaGB\tileProjectFiles\ctaTilesBkg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 10
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define ctagbMapWidth 32
#define ctagbMapHeight 32
#define ctagbMapBank 0

extern unsigned char ctagbMap[];

/* End of CTAGBMAP.H */
