//AUTOGENERATED FILE FROM png2asset
// Conversion args: gameOverMap.png -map

#ifndef METASPRITE_gameOverMap_H
#define METASPRITE_gameOverMap_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define gameOverMap_TILE_ORIGIN 0
#define gameOverMap_TILE_W 8
#define gameOverMap_TILE_H 8
#define gameOverMap_WIDTH 160
#define gameOverMap_HEIGHT 144
#define gameOverMap_TILE_COUNT 41
#define gameOverMap_PALETTE_COUNT 1
#define gameOverMap_COLORS_PER_PALETTE 4
#define gameOverMap_TOTAL_COLORS 4
#define gameOverMap_MAP_ATTRIBUTES 0
extern const unsigned char gameOverMap_map[360];
#define gameOverMap_map_attributes gameOverMap_map

BANKREF_EXTERN(gameOverMap)

extern const palette_color_t gameOverMap_palettes[4];
extern const uint8_t gameOverMap_tiles[656];

#endif
