/*

 STARTMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : C:\c\ctaGB\tileProjectFiles\startTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 26
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __startMap_h_INCLUDE
#define __startMap_h_INCLUDE

#define startMapWidth 32
#define startMapHeight 32
#define startMapBank 0

extern const unsigned char startMap[];

#endif

/* End of STARTMAP.H */
